### PR TITLE
feat: add assert_stderr and assert_stderr_line

### LINKED ISSUE #42: Missing `assert_stderr` and similar assertions
The `run` command in `bats-core` has the ability to keep stderr-related output into separate variables:
> Use `--separate-stderr` to split stdout and stderr into `$output`/`$stderr` and `${lines[@]}`/`${stderr_lines[@]}`

as per https://bats-core.readthedocs.io/en/latest/writing-tests.html#run-test-other-commands

Should we have assertion helpers that apply to stderr only?

### PR DESCRIPTION
**Pull request by adoyle-h**
fix #42

### CODE REVIEW

**Comment by adoyle-h** [comment]
@martin-schulze-vireso This PR is ready. Can you review it?

**Review by martin-schulze-vireso — CHANGES_REQUESTED** [review]
I really dislike the amount of code duplication. Can we have a central implementation that is used by both assert_output and assert_stderr (and _lines likewise)? Similarly, I'd fold the documentation into assert_output's or link to it from there. Feature changes will sooner or later get lost on one of the two duplicates.

**Comment by martin-schulze-vireso** [comment]
@adoyle-h Do you plan to work on this?

**Comment by adoyle-h** [comment]
Sorry, I'm occupied with work.

**Comment by nicola-lunghi** [comment]
Hi @martin-schulze-vireso 
just stumbled on this
can we reopen this so we can fix it?

**Comment by martin-schulze-vireso** [comment]
If you are willing to work in this, you can use the code as starting point but have to open your own PR.

**Comment by nicola-lunghi** [comment]
> If you are willing to work in this, you can use the code as starting point but have to open your own PR.
> 
> I don't have the time to do so myself right now.

Hi @martin-schulze-vireso started working on this
what about a --stderr option in assert_output?
```
assert_output --stderr "My stderr out"
```
I think this wil allows to reuse most of assert_output in https://github.com/bats-core/bats-assert/blob/e2d855bc78619ee15b0c702b5c30fb074101159f/src/assert_output.bash#L124
also we can define an "alias" for `assert_stderr => assert_output --stderr`

**Comment by nicola-lunghi** [comment]
see https://github.com/bats-core/bats-assert/pull/69

**Comment by mh182** [comment]
> I really dislike the amount of code duplication. Can we have a central implementation that is used by both assert_output and assert_stderr (and _lines likewise)? Similarly, I'd fold the documentation into assert_output's or link to it from there. Feature changes will sooner or later get lost on one of the two duplicates.

I addressed your feedback and refactored the code of this pull request. I refactored the existing assert_* functions to handle stdout and stderr streams.

**Pull request closed without merging**
